version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16 
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Building the application...
  post_build:
    commands:
      - echo Build completed successfully!
